baseUrl = "/educacion-latam/"
title = "Educación Latam"
theme = "hugo-titi"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
publishDir = "./docs/"

[menu]
  [[menu.burger]]
    name = "Inicio"
    url = "/"
    weight = 1

[params]
  # SEO general site description
  description = "Site SEO description"

  [params.nav]
    bg = "#ffffff"
    color = "#105EAD"
    logo = "images/logo-bid.png"
    logoWidth = "150px"
    # Optional, true by default
    # fixed = true

  [[params.social]]
    icon = "twitter"
    url = "https://twitter.com/bideducacion"
  [[params.social]]
    icon = "rss"
    url = "https://blogs.iadb.org/educacion/"

  [params.footer]
    text = ""
    bg = "black"
    color = "white"
